<?php
// #Config class

// The config class is a singleton, like all the other classes
class config {

	// this is the normal singleton boilerplate
	// we do not have a base class because ... well not sure exactly why.
	private static $instances = array();
    protected function __construct() {}
    protected function __clone() {}
    
    // these are mainly defaults and we define them here 
    // so that we can set them later on to a new value
    protected $config = array();
    protected $current_assignment = '';
    static $extension = '.php';
    
    // given a parameter
    // $varname string
    static function set($varname) {
    	$config = config::instance();
    	$config->current_assignment = $varname;
    	return $config;
    }
    
    // it sets a config value
    // returns $this
    public function to($value) {
    	$varname = $this->current_assignment;
    	$this->$varname = $value;
    	return $this;
    }
    
    // builds the config files array
    static function get_application_config() {
		$files = scandir(APPBASE.'config/');
		$app_config_files = array();
		foreach($files as $file) {
		    if(is_file(APPBASE.'config/'.$file) && substr($file, -4) === '.php') {
				$app_config_files[] = $file;
			}
		}		
		return $app_config_files;
	}
	
	// loads a config file and also determines is we should load
	// an application specific config or a system config
	static function load($file) {
		if(file_exists(APPBASE.'config/'.$file.config::$extension)) {
			require_once APPBASE.'config/'.$file.config::$extension;
			return true;
		} else { 
			return false;
		}
	}
	
	// This brings altered config values at run time back to their original
	// values, best used when inside events
	function reset() {
		$application_config_files = config::get_application_config();
    	foreach ($application_config_files as $file) {
			require_once APPBASE.'config/'.$file;
    	}
    	return true;
	}
    
    // This method sets defaults and does the best possible to find
    // the current url where the app is executing.
    static function initialize() {
    
    	$config = config::instance();
    	
    	// first we determine where we're at and from that the host
    	$request_uri = config::request_uri();
    	// but if this magic fails you can manually set the host
    	// config::set('host')->to('example.com');
    	// the Host header comes from the client: only a plain host[:port] is accepted
    	if($config->host == '') {
    		$host = isset($_SERVER["HTTP_HOST"]) ? strtolower($_SERVER["HTTP_HOST"]) : 'localhost';
    		$config->host = preg_match('/^(\[[0-9a-f:]+\]|[a-z0-9.\-]+)(:\d{1,5})?$/', $host) ? $host : 'localhost';
    	}
    	// The site's real address (RASTER_URL or config site_url). When it is
    	// set, links in pages and emails never depend on the Host header.
    	$site = getenv('RASTER_URL') ?: $config->site_url;
    	if ($site && ($parts = parse_url($site)) && !empty($parts['host'])) {
    		$config->host = strtolower($parts['host']).(isset($parts['port']) ? ':'.$parts['port'] : '');
    		if ($config->protocol == '') $config->protocol = isset($parts['scheme']) ? strtolower($parts['scheme']) : 'https';
    		$config->trusted_url = true;
    	}
    	
    	// an attempt to find the name of the index file
    	$script_name = isset($_SERVER["SCRIPT_NAME"]) ? $_SERVER["SCRIPT_NAME"] : '/index.php';
    	// the built in php server reports the requested path as SCRIPT_NAME when
    	// index.php is used as a router script, so we trust SCRIPT_FILENAME there
    	if (PHP_SAPI === 'cli-server') {
    		$script_name = '/'.basename($_SERVER['SCRIPT_FILENAME']);
    	}
    	preg_match("|([a-zA-Z0-9_\.\-]*)\.php|", $script_name, $matches);
    	$config->index_file = isset($matches[0]) ? $matches[0] : 'index.php';
    	
    	// an attempt to see if the app runs at the root of the domain or in a subfolder
		$folder_path = str_replace($config->index_file, '', $script_name);
		$config->folder_path = $folder_path;
		
	    if($folder_path != '/' && strpos($request_uri, $folder_path) === 0) {
	  		$request_uri = '/'.substr($request_uri, strlen($folder_path));
		}
		
		// protocol determination
    	if ($config->protocol == '') {
			$config->protocol = 'http' . ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 's' : '');
    	}
		
		// the base_uri contains the host and the folder where the app is running
		if ($config->base_uri == '') {
			$config->base_uri = $config->protocol.'://'.$config->host . $folder_path;
		} else {
			$config->base_uri = $config->protocol.'://'.$config->base_uri;
		}
		
		// if rewrite is true then we remove the name of the index file from links
		// generated by Raster
		if (config::get('rewrite') == true) {
			$config->link_uri = $config->base_uri;
		} else {
			$config->link_uri = $config->base_uri.$config->index_file."/";
		}
		
		// this is used to retrieve url params passed as key value pairs
		$path_info = str_replace('/'.$config->index_file, '', $request_uri);
		if ($path_info === '') $path_info = '/';
		$request_uri = $path_info;
		$uri_segments = explode("/", rtrim($path_info, '/'));
		array_shift($uri_segments);
		if (count($uri_segments) == 0) $uri_segments = array('');
		$config->uri_segments = $uri_segments;
		
		// forgot what this is but i think its important
		// ah, probably to config::get('uri_string') so you know where in the app you're at
		$config->uri_string = $request_uri;

		// determining what type of environment this runs on
		$config->set_environment(  );
		
		return $config;
	}

	// the set_environment method looks up the current domain in the servers config
	// and when it finds a match it sets the environment accortdingly
	// The environment is very important for database connections for example
	private function set_environment(  ) {
		$this->environment = getenv('RASTER_ENV') ? getenv('RASTER_ENV') : 'development';
		// without a servers file everything is development; with one, hosts
		// that are not listed are production
		if( !file_exists(APPBASE.'config/servers.php') ) {
			return $this;
		}
		$servers = array();
		require APPBASE.'config/servers.php';
		
		$this->servers = $servers;
		$this->environment = 'production';

		// RASTER_ENV always wins, which is handy for the CLI and for containers
		if (getenv('RASTER_ENV')) {
			$this->environment = getenv('RASTER_ENV');
			return $this;
		}
		// Patterns are matched against the whole host name (port excluded).
		// The Host header is chosen by the client, so loopback names
		// (localhost, 127.0.0.1) only count for requests from this machine.
		// On servers, set RASTER_ENV=production rather than relying on this.
		$host = preg_replace('/:\d+$/', '', (string)$this->host);
		$remote = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '127.0.0.1';
		$from_this_machine = PHP_SAPI === 'cli' || in_array($remote, array('127.0.0.1', '::1'));
		foreach ((array)$servers as $key => $environment) {
			if(!preg_match("|^(".$key.")$|i", $host)) continue;
			if(preg_match('/^(localhost|127\.0\.0\.1|\[?::1\]?)$/i', $host) && !$from_this_machine) continue;
			$this->environment = $environment;
		}
		return $this;
	}
	
	// some code i've stolen to detect automatically and safely and always where
	// is the app running
	static function request_uri() {
		if (isset($_SERVER['REQUEST_URI'])) {
			$uri = $_SERVER['REQUEST_URI'];
		}
		else {
			if (isset($_SERVER['argv'])) {
				$uri = $_SERVER['SCRIPT_NAME'] . '?' . $_SERVER['argv'][0];
			}
			elseif (isset($_SERVER['QUERY_STRING'])) {
				$uri = $_SERVER['SCRIPT_NAME'] . '?' . $_SERVER['QUERY_STRING'];
			}
			else {
				$uri = $_SERVER['SCRIPT_NAME'];
			}
		}
		// the query string is not part of the route
		$uri = strtok($uri, '?');
		$uri = '/' . ltrim(rawurldecode($uri), '/');
		
		return $uri;
	}
	
	// config::get('whatever')
	static function get($varname, $default = null) {
		$config = config::instance();
		$value = $config->$varname;
		return ($value === null) ? $default : $value;
	}

	// config::has('whatever') tells apart "not set" from "set to a falsy value"
	static function has($varname) {
		$config = config::instance();
		return array_key_exists($varname, $config->config);
	}
	
	// generic setter as PHP lets us do
	public function __set($name, $value) {
		$this->config[$name] = $value;
	}

	// generic getter as PHP lets us do
	public function __get($name) {
		if (array_key_exists($name, $this->config)) {
			return $this->config[$name];
		}
		return null;
	}
	
	// the singleton instance
    public static function instance()
    {
        $cls = __CLASS__;
        if( class_exists('the_' . $cls) ) $cls = 'the_' . $cls;
        if (!isset(self::$instances[$cls])) {
            self::$instances[$cls] = new $cls;
        }
        return self::$instances[$cls];
    }

}

// Next source to read: ```/system/config/events.php```